# Build settings
theme: jekyll-theme-cayman-blog
markdown: kramdown

# basic options
title: SmartLoad
author: Keshav Vasudevan
email: keshav.vasudevan@smartbear.com
description: SmartLoad your websites like never before!
twitter_username: keshinpoint
github_username: kesh92
repository: kesh92/keshinpoint
cta_url: https://swagger.io
